require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe GawksController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Gawk. As you add validations to Gawk, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GawksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all gawks as @gawks" do
      gawk = Gawk.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:gawks)).to eq([gawk])
    end
  end

  describe "GET show" do
    it "assigns the requested gawk as @gawk" do
      gawk = Gawk.create! valid_attributes
      get :show, {:id => gawk.to_param}, valid_session
      expect(assigns(:gawk)).to eq(gawk)
    end
  end

  describe "GET new" do
    it "assigns a new gawk as @gawk" do
      get :new, {}, valid_session
      expect(assigns(:gawk)).to be_a_new(Gawk)
    end
  end

  describe "GET edit" do
    it "assigns the requested gawk as @gawk" do
      gawk = Gawk.create! valid_attributes
      get :edit, {:id => gawk.to_param}, valid_session
      expect(assigns(:gawk)).to eq(gawk)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Gawk" do
        expect {
          post :create, {:gawk => valid_attributes}, valid_session
        }.to change(Gawk, :count).by(1)
      end

      it "assigns a newly created gawk as @gawk" do
        post :create, {:gawk => valid_attributes}, valid_session
        expect(assigns(:gawk)).to be_a(Gawk)
        expect(assigns(:gawk)).to be_persisted
      end

      it "redirects to the created gawk" do
        post :create, {:gawk => valid_attributes}, valid_session
        expect(response).to redirect_to(Gawk.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved gawk as @gawk" do
        post :create, {:gawk => invalid_attributes}, valid_session
        expect(assigns(:gawk)).to be_a_new(Gawk)
      end

      it "re-renders the 'new' template" do
        post :create, {:gawk => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested gawk" do
        gawk = Gawk.create! valid_attributes
        put :update, {:id => gawk.to_param, :gawk => new_attributes}, valid_session
        gawk.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested gawk as @gawk" do
        gawk = Gawk.create! valid_attributes
        put :update, {:id => gawk.to_param, :gawk => valid_attributes}, valid_session
        expect(assigns(:gawk)).to eq(gawk)
      end

      it "redirects to the gawk" do
        gawk = Gawk.create! valid_attributes
        put :update, {:id => gawk.to_param, :gawk => valid_attributes}, valid_session
        expect(response).to redirect_to(gawk)
      end
    end

    describe "with invalid params" do
      it "assigns the gawk as @gawk" do
        gawk = Gawk.create! valid_attributes
        put :update, {:id => gawk.to_param, :gawk => invalid_attributes}, valid_session
        expect(assigns(:gawk)).to eq(gawk)
      end

      it "re-renders the 'edit' template" do
        gawk = Gawk.create! valid_attributes
        put :update, {:id => gawk.to_param, :gawk => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested gawk" do
      gawk = Gawk.create! valid_attributes
      expect {
        delete :destroy, {:id => gawk.to_param}, valid_session
      }.to change(Gawk, :count).by(-1)
    end

    it "redirects to the gawks list" do
      gawk = Gawk.create! valid_attributes
      delete :destroy, {:id => gawk.to_param}, valid_session
      expect(response).to redirect_to(gawks_url)
    end
  end

end
